---
framework: jest
preRun:
     env:
        - TEST: true 
        - REACT: 15
     command:
        - npm install
        - npm run react
preMerge:
  env:
    --testEnvironment: node
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postMerge: 
  env:
    --testEnvironment: node
  pattern: 
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postRun:
     command:
        - node --version
nodeVersion: 14.18.1
version: 1.0
