---
framework: jest
preRun:
     command:
        - export TEST=true
        - export REACT=0.14
        - nvm install 10
        - node --version
        - npm --version
        - nvm --version
        - nvm install-latest-npm
        - npm run react
        - enzyme-adapter-react-install 16
preMerge:
  env:
    --testEnvironment: node
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postMerge: 
  env:
    --testEnvironment: node
  pattern: 
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postRun:
     command:
        - node --version
version: 1.0
