---
framework: jest
preRun:
     command:
        - npm i
        - npm run react
preMerge:
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
postMerge: 
  pattern: 
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
postRun:
     command:
        - node --version
nodeVersion: 14.18.1
version: 1.0.0
