---
framework: jest
preRun:
     command:
        - npm i
        - npm run react
        - enzyme-adapter-react-install 16
preMerge:
  env:
    --testEnvironment: node
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postMerge: 
  env:
    --testEnvironment: node
  pattern: 
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/new-test.js"
postRun:
     command:
        - node --version
nodeVersion: 14.18.1
version: 1.0
